stages:
  - lint
  - build
  - test
  - review

api-visibility:
  stage: lint
  script:
    # Check that private headers aren't included in public ones.
    - if grep "include.*private.h" $(ls retro-gtk/*.h | grep -v private);
      then
        echo "Private headers shouldn't be included in public ones.";
        exit 1;
      fi
    # Check that retro-gtk.h contains all the public headers.
    - for header in $(ls retro-gtk | grep \.h$ | grep -v private | grep -v retro-gtk.h);
      do
        if ! grep -q "$header" retro-gtk/retro-gtk.h;
        then
          echo "The public header" $header "should be included in retro-gtk.h.";
          exit 1;
        fi;
      done

variables:
  BUNDLE: "retro-demo-samples-test-git.flatpak"

flatpak:tests:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: test
  variables:
    MANIFEST_PATH: "flatpak/org.gnome.Retro.UnitTests.json"
    FLATPAK_MODULE: "retro-gtk"
    FLATPAK_BUILD_DIR: "unit-tests"
    MESON_ARGS: "--libdir=lib -Dinstall-tests=true"
  script:
    - flatpak-builder --stop-at=${FLATPAK_MODULE} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - flatpak build ${FLATPAK_BUILD_DIR} meson --prefix=/app ${MESON_ARGS} _build
    - flatpak build ${FLATPAK_BUILD_DIR} ninja -C _build install
    - flatpak-builder --finish-only --repo=repo ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - xvfb-run -a -s "-screen 0 1024x768x24" flatpak-builder --run unit-tests ${MANIFEST_PATH} retro-unit-tests
  cache:
    paths:
      - .flatpak-builder/cache/

flatpak:demo:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: build
  variables:
    MANIFEST_PATH: "flatpak/org.gnome.Retro.DemoSamplesTest.json"
    RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
    FLATPAK_MODULE: "retro-gtk"
    FLATPAK_BUILD_DIR: "app"
    MESON_ARGS: ""
  script:
    - flatpak-builder --stop-at=${FLATPAK_MODULE} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - flatpak build ${FLATPAK_BUILD_DIR} meson --prefix=/app ${MESON_ARGS} _build
    - flatpak build ${FLATPAK_BUILD_DIR} ninja -C _build install
    - flatpak-builder --finish-only --repo=repo ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} org.gnome.Retro.DemoSamplesTest
  artifacts:
    paths:
      - ${BUNDLE}
      - _build/meson-logs/meson-log.txt
    expire_in: 2 days
  cache:
    paths:
      - .flatpak-builder/cache/

review:
  stage: review
  dependencies:
    - flatpak:demo
    - flatpak:tests
  script:
    - echo "Generating flatpak deployment"
  artifacts:
    paths:
      - ${BUNDLE}
    expire_in: 30 days
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://gitlab.gnome.org/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/raw/${BUNDLE}
    on_stop: stop_review
  except:
    - master@GNOME/retro-gtk
    - gnome-3-.*
    - tags

stop_review:
  stage: review
  script:
    - echo "Stopping flatpak deployment"
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  except:
    - master@GNOME/retro-gtk
    - gnome-3-.*
    - tags
