stages:
  - pre
  - build
  - test
  - publish

lint:
  stage: pre
  script:
    - tools/check-api-visibility.sh

variables:
  BUNDLE: "retro-demo-samples-test-git.flatpak"

flatpak:tests:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: test
  tags:
    - flatpak
  variables:
    MANIFEST_PATH: "flatpak/org.gnome.Retro.UnitTests.json"
    FLATPAK_MODULE: "retro-gtk"
    FLATPAK_BUILD_DIR: "unit-tests"
    MESON_ARGS: "--libdir=lib -Dinstall-tests=true -Dpulseaudio=disabled"
  script:
    - flatpak-builder --user --disable-rofiles-fuse --stop-at=${FLATPAK_MODULE} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - flatpak build ${FLATPAK_BUILD_DIR} meson --prefix=/app ${MESON_ARGS} _build_tests
    - flatpak build ${FLATPAK_BUILD_DIR} ninja -C _build_tests install
    - flatpak-builder --user --disable-rofiles-fuse --finish-only --repo=repo ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - xvfb-run -a -s "-screen 0 1024x768x24" flatpak-builder --disable-rofiles-fuse --run unit-tests ${MANIFEST_PATH} retro-unit-tests

flatpak:demo:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: build
  tags:
    - flatpak
  variables:
    MANIFEST_PATH: "flatpak/org.gnome.Retro.DemoSamplesTest.json"
    RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
    FLATPAK_MODULE: "retro-gtk"
    FLATPAK_BUILD_DIR: "app"
    MESON_ARGS: ""
  script:
    - flatpak-builder --user --disable-rofiles-fuse --stop-at=${FLATPAK_MODULE} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - flatpak build ${FLATPAK_BUILD_DIR} meson --prefix=/app ${MESON_ARGS} _build
    - flatpak build ${FLATPAK_BUILD_DIR} ninja -C _build install
    - flatpak-builder --user --disable-rofiles-fuse --finish-only --repo=repo ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} org.gnome.Retro.DemoSamplesTest
  artifacts:
    paths:
      - ${BUNDLE}
      - _build/meson-logs/meson-log.txt
    expire_in: 2 days

reference:
  image: registry.gitlab.gnome.org/gnome/gtk/fedora:v16
  stage: build
  variables:
    MESON_ARGS: "--buildtype=release --libdir=lib -Dpulseaudio=disabled -Dintrospection=false -Dbuild-tests=false -Dbuild-doc=true"
  script:
    - meson ${MESON_ARGS} _build
    - ninja -C _build retro-gtk-doc
    - mv _build/doc/html/ _reference/
  artifacts:
    paths:
      - _reference
