
.build_template: &distro_build
  script:
    - meson -Dmanpage=false _build
    - ninja -C _build install

stages:
  - build-flatpak

flatpak:unit-tests:
  image: registry.gitlab.gnome.org/gnome/gnome-nightly-oci/nightly:master
  stage: build-flatpak
  variables:
    MANIFEST_PATH: "flatpak/org.gnome.Retro.UnitTests.json"
    FLATPAK_MODULE: "retro-gtk"
    FLATPAK_BUILD_DIR: "unit-tests"
    MESON_ARGS: "--libdir=lib -Dinstall-tests=true"
  script:
    - flatpak-builder --stop-at=${FLATPAK_MODULE} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - flatpak build ${FLATPAK_BUILD_DIR} meson --prefix=/app ${MESON_ARGS} _build
    - flatpak build ${FLATPAK_BUILD_DIR} ninja -C _build install
    - flatpak-builder --finish-only --repo=repo ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - xvfb-run -a -s "-screen 0 1024x768x24" flatpak-builder --run unit-tests ${MANIFEST_PATH} retro-unit-tests
  cache:
    paths:
      - .flatpak-builder/cache/

flatpak:demo-samples-test:
  image: registry.gitlab.gnome.org/gnome/gnome-nightly-oci/nightly:master
  stage: build-flatpak
  variables:
    MANIFEST_PATH: "flatpak/org.gnome.Retro.DemoSamplesTest.json"
    RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
    FLATPAK_MODULE: "retro-gtk"
    FLATPAK_BUILD_DIR: "app"
    BUNDLE: "retro-demo-samples-test-git.flatpak"
  script:
    - flatpak-builder --stop-at=${FLATPAK_MODULE} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - flatpak build ${FLATPAK_BUILD_DIR} meson --prefix=/app ${MESON_ARGS} _build
    - flatpak build ${FLATPAK_BUILD_DIR} ninja -C _build install
    - flatpak-builder --finish-only --repo=repo ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} org.gnome.Retro.DemoSamplesTest

  artifacts:
    paths:
      - ${BUNDLE}
      - _build/meson-logs/meson-log.txt
    expire_in: 2 days
  cache:
    paths:
      - .flatpak-builder/cache/
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://gitlab.gnome.org/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/raw/${BUNDLE}
