include: https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml

stages:
  - pre
  - build

variables:
  FLATPAK_BUILD_DIR: app
  FLATPAK_MODULE: retro-gtk
  MANIFEST_PATH: flatpak/org.gnome.Retro.UnitTests.json
  SHARED_MESON_ARGS: >-
    --buildtype=release
    -Dpulseaudio=disabled

lint:
  stage: pre
  script:
    - tools/check-api-visibility.sh

dependencies:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: pre
  tags:
    - flatpak
  script:
    - flatpak-builder --user --disable-rofiles-fuse --stop-at=${FLATPAK_MODULE} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
  artifacts:
    paths:
      - ${FLATPAK_BUILD_DIR}

unit-tests:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: build
  tags:
    - flatpak
  variables:
    FLATPAK_BUILD_DIR: unit-tests
    MESON_ARGS: >-
      -Dinstall-tests=true
  script:
    # Somehow we need to rebuild the Flatpak here, in a different dir, otherwise installing it will fail.
    - flatpak-builder --user --disable-rofiles-fuse --stop-at=${FLATPAK_MODULE} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - flatpak build ${FLATPAK_BUILD_DIR} meson --prefix=/app ${SHARED_MESON_ARGS} ${MESON_ARGS} _build
    - flatpak build ${FLATPAK_BUILD_DIR} ninja -C _build install
    - flatpak-builder --user --disable-rofiles-fuse --finish-only --repo=repo ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - xvfb-run -a -s "-screen 0 1024x768x24" flatpak-builder --disable-rofiles-fuse --run ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH} retro-unit-tests

doc:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: build
  dependencies:
    - dependencies
  tags:
    - flatpak
  variables:
    MESON_ARGS: >-
      -Dbuild-doc=true
      -Dbuild-tests=false
      -Dintrospection=false
  script:
    - flatpak build ${FLATPAK_BUILD_DIR} meson --prefix=/app ${SHARED_MESON_ARGS} ${MESON_ARGS} _build
    - flatpak build ${FLATPAK_BUILD_DIR} ninja -C _build retro-gtk-doc
    - mv _build/doc/html/ _doc/
  artifacts:
    paths:
      - _doc
