
.build_template: &distro_build
  script:
    - meson -Dmanpage=false _build
    - ninja -C _build install

stages:
  - build-flatpak

flatpak:unit-tests:
  image: registry.gitlab.com/alatiera/gnome-nightly-oci/gnome-master:latest
  stage: build-flatpak
  script:
    - flatpak-builder unit-tests flatpak/org.gnome.Retro.UnitTests.json
    - xvfb-run -a -s "-screen 0 1024x768x24" flatpak-builder --run unit-tests flatpak/org.gnome.Retro.UnitTests.json retro-unit-tests

flatpak:demo-samples-test:
  image: registry.gitlab.com/alatiera/gnome-nightly-oci/gnome-master:latest
  stage: build-flatpak
  script:
    - flatpak-builder --repo=repo demo-samples-test flatpak/org.gnome.Retro.DemoSamplesTest.json
    - flatpak build-bundle repo retro-demo-samples-test.flatpak org.gnome.Retro.DemoSamplesTest

  artifacts:
    paths:
      - retro-demo-samples-test.flatpak
    expire_in: 2 days
