// This file is part of retro-gtk. License: GPL-3.0+.

#include "retro-keyboard-private.h"

#include <linux/input-event-codes.h>

RetroKeyboardModifierKey
retro_keyboard_modifier_key_converter (guint           keyval,
                                       GdkModifierType modifiers)
{
  RetroKeyboardModifierKey retro_modifiers = RETRO_KEYBOARD_MODIFIER_KEY_NONE;

  if (modifiers & GDK_SHIFT_MASK)
    retro_modifiers |= RETRO_KEYBOARD_MODIFIER_KEY_SHIFT;
  if (modifiers & GDK_CONTROL_MASK)
    retro_modifiers |= RETRO_KEYBOARD_MODIFIER_KEY_CTRL;
  if (modifiers & GDK_MOD1_MASK)
    retro_modifiers |= RETRO_KEYBOARD_MODIFIER_KEY_ALT;
  if (modifiers & GDK_META_MASK)
    retro_modifiers |= RETRO_KEYBOARD_MODIFIER_KEY_META;
  if (keyval == GDK_KEY_Num_Lock)
    retro_modifiers |= RETRO_KEYBOARD_MODIFIER_KEY_NUMLOCK;
  if (modifiers & GDK_LOCK_MASK)
    retro_modifiers |= RETRO_KEYBOARD_MODIFIER_KEY_CAPSLOCK;
  if (keyval == GDK_KEY_Scroll_Lock)
    retro_modifiers |= RETRO_KEYBOARD_MODIFIER_KEY_SCROLLOCK;

  return retro_modifiers;
}


RetroKeyboardKey
retro_keyboard_key_converter (guint16 keycode)
{
  /* Mappings of the 0x100 first Linux input event key codes to the corresponding
   * Libretro keyboard code.
   */
  static const RetroKeyboardKey keycode_mappings[] = {
    RETRO_KEYBOARD_KEY_FIRST, /* KEY_RESERVED */
    RETRO_KEYBOARD_KEY_ESCAPE, /* KEY_ESC */
    RETRO_KEYBOARD_KEY_ONE, /* KEY_1 */
    RETRO_KEYBOARD_KEY_TWO, /* KEY_2 */
    RETRO_KEYBOARD_KEY_THREE, /* KEY_3 */
    RETRO_KEYBOARD_KEY_FOUR, /* KEY_4 */
    RETRO_KEYBOARD_KEY_FIVE, /* KEY_5 */
    RETRO_KEYBOARD_KEY_SIX, /* KEY_6 */
    RETRO_KEYBOARD_KEY_SEVEN, /* KEY_7 */
    RETRO_KEYBOARD_KEY_EIGHT, /* KEY_8 */
    RETRO_KEYBOARD_KEY_NINE, /* KEY_9 */
    RETRO_KEYBOARD_KEY_ZERO, /* KEY_0 */
    RETRO_KEYBOARD_KEY_MINUS, /* KEY_MINUS */
    RETRO_KEYBOARD_KEY_EQUALS, /* KEY_EQUAL */
    RETRO_KEYBOARD_KEY_BACKSPACE, /* KEY_BACKSPACE */
    RETRO_KEYBOARD_KEY_TAB, /* KEY_TAB */
    RETRO_KEYBOARD_KEY_q, /* KEY_Q */
    RETRO_KEYBOARD_KEY_w, /* KEY_W */
    RETRO_KEYBOARD_KEY_e, /* KEY_E */
    RETRO_KEYBOARD_KEY_r, /* KEY_R */
    RETRO_KEYBOARD_KEY_t, /* KEY_T */
    RETRO_KEYBOARD_KEY_y, /* KEY_Y */
    RETRO_KEYBOARD_KEY_u, /* KEY_U */
    RETRO_KEYBOARD_KEY_i, /* KEY_I */
    RETRO_KEYBOARD_KEY_o, /* KEY_O */
    RETRO_KEYBOARD_KEY_p, /* KEY_P */
    RETRO_KEYBOARD_KEY_LEFTBRACE, /* KEY_LEFTBRACE */
    RETRO_KEYBOARD_KEY_RIGHTBRACE, /* KEY_RIGHTBRACE */
    RETRO_KEYBOARD_KEY_RETURN, /* KEY_ENTER */
    RETRO_KEYBOARD_KEY_LCTRL, /* KEY_LEFTCTRL */
    RETRO_KEYBOARD_KEY_a, /* KEY_A */
    RETRO_KEYBOARD_KEY_s, /* KEY_S */
    RETRO_KEYBOARD_KEY_d, /* KEY_D */
    RETRO_KEYBOARD_KEY_f, /* KEY_F */
    RETRO_KEYBOARD_KEY_g, /* KEY_G */
    RETRO_KEYBOARD_KEY_h, /* KEY_H */
    RETRO_KEYBOARD_KEY_j, /* KEY_J */
    RETRO_KEYBOARD_KEY_k, /* KEY_K */
    RETRO_KEYBOARD_KEY_l, /* KEY_L */
    RETRO_KEYBOARD_KEY_SEMICOLON, /* KEY_SEMICOLON */
    RETRO_KEYBOARD_KEY_QUOTE, /* KEY_APOSTROPHE */
    RETRO_KEYBOARD_KEY_BACKQUOTE, /* KEY_GRAVE */
    RETRO_KEYBOARD_KEY_LSHIFT, /* KEY_LEFTSHIFT */
    RETRO_KEYBOARD_KEY_BACKSLASH, /* KEY_BACKSLASH */
    RETRO_KEYBOARD_KEY_z, /* KEY_Z */
    RETRO_KEYBOARD_KEY_x, /* KEY_X */
    RETRO_KEYBOARD_KEY_c, /* KEY_C */
    RETRO_KEYBOARD_KEY_v, /* KEY_V */
    RETRO_KEYBOARD_KEY_b, /* KEY_B */
    RETRO_KEYBOARD_KEY_n, /* KEY_N */
    RETRO_KEYBOARD_KEY_m, /* KEY_M */
    RETRO_KEYBOARD_KEY_COMMA, /* KEY_COMMA */
    RETRO_KEYBOARD_KEY_PERIOD, /* KEY_DOT */
    RETRO_KEYBOARD_KEY_SLASH, /* KEY_SLASH */
    RETRO_KEYBOARD_KEY_RSHIFT, /* KEY_RIGHTSHIFT */
    RETRO_KEYBOARD_KEY_KP_MULTIPLY, /* KEY_KPASTERISK */
    RETRO_KEYBOARD_KEY_LALT, /* KEY_LEFTALT */
    RETRO_KEYBOARD_KEY_SPACE, /* KEY_SPACE */
    RETRO_KEYBOARD_KEY_CAPSLOCK, /* KEY_CAPSLOCK */
    RETRO_KEYBOARD_KEY_F1, /* KEY_F1 */
    RETRO_KEYBOARD_KEY_F2, /* KEY_F2 */
    RETRO_KEYBOARD_KEY_F3, /* KEY_F3 */
    RETRO_KEYBOARD_KEY_F4, /* KEY_F4 */
    RETRO_KEYBOARD_KEY_F5, /* KEY_F5 */
    RETRO_KEYBOARD_KEY_F6, /* KEY_F6 */
    RETRO_KEYBOARD_KEY_F7, /* KEY_F7 */
    RETRO_KEYBOARD_KEY_F8, /* KEY_F8 */
    RETRO_KEYBOARD_KEY_F9, /* KEY_F9 */
    RETRO_KEYBOARD_KEY_F10, /* KEY_F10 */
    RETRO_KEYBOARD_KEY_NUMLOCK, /* KEY_NUMLOCK */
    RETRO_KEYBOARD_KEY_SCROLLOCK, /* KEY_SCROLLLOCK */
    RETRO_KEYBOARD_KEY_KP7, /* KEY_KP7 */
    RETRO_KEYBOARD_KEY_KP8, /* KEY_KP8 */
    RETRO_KEYBOARD_KEY_KP9, /* KEY_KP9 */
    RETRO_KEYBOARD_KEY_KP_MINUS, /* KEY_KPMINUS */
    RETRO_KEYBOARD_KEY_KP4, /* KEY_KP4 */
    RETRO_KEYBOARD_KEY_KP5, /* KEY_KP5 */
    RETRO_KEYBOARD_KEY_KP6, /* KEY_KP6 */
    RETRO_KEYBOARD_KEY_KP_PLUS, /* KEY_KPPLUS */
    RETRO_KEYBOARD_KEY_KP1, /* KEY_KP1 */
    RETRO_KEYBOARD_KEY_KP2, /* KEY_KP2 */
    RETRO_KEYBOARD_KEY_KP3, /* KEY_KP3 */
    RETRO_KEYBOARD_KEY_KP0, /* KEY_KP0 */
    RETRO_KEYBOARD_KEY_KP_PERIOD, /* KEY_KPDOT */
    RETRO_KEYBOARD_KEY_UNKNOWN,
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_ZENKAKUHANKAKU */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_102ND */
    RETRO_KEYBOARD_KEY_F11, /* KEY_F11 */
    RETRO_KEYBOARD_KEY_F12, /* KEY_F12 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_RO */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_KATAKANA */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_HIRAGANA */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_HENKAN */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_KATAKANAHIRAGANA */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_MUHENKAN */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_KPJPCOMMA */
    RETRO_KEYBOARD_KEY_KP_ENTER, /* KEY_KPENTER */
    RETRO_KEYBOARD_KEY_RCTRL, /* KEY_RIGHTCTRL */
    RETRO_KEYBOARD_KEY_KP_DIVIDE, /* KEY_KPSLASH */
    RETRO_KEYBOARD_KEY_SYSREQ, /* KEY_SYSRQ */
    RETRO_KEYBOARD_KEY_RALT, /* KEY_RIGHTALT */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_LINEFEED */
    RETRO_KEYBOARD_KEY_HOME, /* KEY_HOME */
    RETRO_KEYBOARD_KEY_UP, /* KEY_UP */
    RETRO_KEYBOARD_KEY_PAGEUP, /* KEY_PAGEUP */
    RETRO_KEYBOARD_KEY_LEFT, /* KEY_LEFT */
    RETRO_KEYBOARD_KEY_RIGHT, /* KEY_RIGHT */
    RETRO_KEYBOARD_KEY_END, /* KEY_END */
    RETRO_KEYBOARD_KEY_DOWN, /* KEY_DOWN */
    RETRO_KEYBOARD_KEY_PAGEDOWN, /* KEY_PAGEDOWN */
    RETRO_KEYBOARD_KEY_INSERT, /* KEY_INSERT */
    RETRO_KEYBOARD_KEY_DELETE, /* KEY_DELETE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_MACRO */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_MUTE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_VOLUMEDOWN */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_VOLUMEUP */
    RETRO_KEYBOARD_KEY_POWER, /* KEY_POWER */
    RETRO_KEYBOARD_KEY_KP_EQUALS, /* KEY_KPEQUAL */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_KPPLUSMINUS */
    RETRO_KEYBOARD_KEY_PAUSE, /* KEY_PAUSE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SCALE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_KPCOMMA */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_HANGEUL, KEY_HANGUEL */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_HANJA */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_YEN */
    RETRO_KEYBOARD_KEY_LSUPER, /* KEY_LEFTMETA */
    RETRO_KEYBOARD_KEY_RSUPER, /* KEY_RIGHTMETA */
    RETRO_KEYBOARD_KEY_COMPOSE, /* KEY_COMPOSE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_STOP */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_AGAIN */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PROPS */
    RETRO_KEYBOARD_KEY_UNDO, /* KEY_UNDO */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_FRONT */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_COPY */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_OPEN */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PASTE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_FIND */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_CUT */
    RETRO_KEYBOARD_KEY_HELP, /* KEY_HELP */
    RETRO_KEYBOARD_KEY_MENU, /* KEY_MENU */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_CALC */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SETUP */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SLEEP */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_WAKEUP */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_FILE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SENDFILE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_DELETEFILE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_XFER */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PROG1 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PROG2 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_WWW */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_MSDOS */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_COFFEE, KEY_SCREENLOCK */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_ROTATE_DISPLAY, KEY_DIRECTION */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_CYCLEWINDOWS */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_MAIL */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_BOOKMARKS */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_COMPUTER */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_BACK */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_FORWARD */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_CLOSECD */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_EJECTCD */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_EJECTCLOSECD */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_NEXTSONG */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PLAYPAUSE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PREVIOUSSONG */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_STOPCD */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_RECORD */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_REWIND */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PHONE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_ISO */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_CONFIG */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_HOMEPAGE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_REFRESH */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_EXIT */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_MOVE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_EDIT */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SCROLLUP */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SCROLLDOWN */
    /* FIXME Check the values for KEY_KPLEFTPAREN and KEY_KPRIGHTPAREN are correct. */
    RETRO_KEYBOARD_KEY_LEFTPAREN, /* KEY_KPLEFTPAREN */
    RETRO_KEYBOARD_KEY_RIGHTPAREN, /* KEY_KPRIGHTPAREN */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_NEW */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_REDO */
    RETRO_KEYBOARD_KEY_F13, /* KEY_F13 */
    RETRO_KEYBOARD_KEY_F14, /* KEY_F14 */
    RETRO_KEYBOARD_KEY_F15, /* KEY_F15 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_F16 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_F17 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_F18 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_F19 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_F20 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_F21 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_F22 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_F23 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_F24 */
    RETRO_KEYBOARD_KEY_UNKNOWN,
    RETRO_KEYBOARD_KEY_UNKNOWN,
    RETRO_KEYBOARD_KEY_UNKNOWN,
    RETRO_KEYBOARD_KEY_UNKNOWN,
    RETRO_KEYBOARD_KEY_UNKNOWN,
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PLAYCD */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PAUSECD */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PROG3 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PROG4 */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_DASHBOARD */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SUSPEND */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_CLOSE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_PLAY */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_FASTFORWARD */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_BASSBOOST */
    RETRO_KEYBOARD_KEY_PRINT, /* KEY_PRINT */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_HP */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_CAMERA */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SOUND */
    RETRO_KEYBOARD_KEY_QUESTION, /* KEY_QUESTION */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_EMAIL */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_CHAT */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SEARCH */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_CONNECT */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_FINANCE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SPORT */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SHOP */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_ALTERASE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_CANCEL */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_BRIGHTNESSDOWN */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_BRIGHTNESSUP */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_MEDIA */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SWITCHVIDEOMODE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_KBDILLUMTOGGLE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_KBDILLUMDOWN */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_KBDILLUMUP */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SEND */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_REPLY */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_FORWARDMAIL */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_SAVE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_DOCUMENTS */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_BATTERY */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_BLUETOOTH */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_WLAN */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_UWB */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_UNKNOWN */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_VIDEO_NEXT */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_VIDEO_PREV */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_BRIGHTNESS_CYCLE */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_BRIGHTNESS_AUTO, KEY_BRIGHTNESS_ZERO */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_DISPLAY_OFF */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_WWAN, KEY_WIMAX */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_RFKILL */
    RETRO_KEYBOARD_KEY_UNKNOWN, /* KEY_MICMUTE */
  };

  /* GDK adds 8 to the Linux input event codes to create the hardware keycode.*/

  g_return_val_if_fail (keycode < 8, RETRO_KEYBOARD_KEY_UNKNOWN);

  keycode -= 8;

  if (keycode < G_N_ELEMENTS (keycode_mappings))
    return keycode_mappings[keycode];

  /* FIXME The following RetroKeyboardKey values are not mapped:
   * - RETRO_KEYBOARD_KEY_AMPERSAND
   * - RETRO_KEYBOARD_KEY_ASTERISK
   * - RETRO_KEYBOARD_KEY_AT
   * - RETRO_KEYBOARD_KEY_BAR
   * - RETRO_KEYBOARD_KEY_CARET
   * - RETRO_KEYBOARD_KEY_COLON
   * - RETRO_KEYBOARD_KEY_EXCLAIM
   * - RETRO_KEYBOARD_KEY_GREATER
   * - RETRO_KEYBOARD_KEY_HASH
   * - RETRO_KEYBOARD_KEY_LAST
   * - RETRO_KEYBOARD_KEY_LEFTBRACKET
   * - RETRO_KEYBOARD_KEY_LESS
   * - RETRO_KEYBOARD_KEY_LMETA
   * - RETRO_KEYBOARD_KEY_PLUS
   * - RETRO_KEYBOARD_KEY_QUOTEDBL
   * - RETRO_KEYBOARD_KEY_RIGHTBRACKET
   * - RETRO_KEYBOARD_KEY_RMETA
   * - RETRO_KEYBOARD_KEY_TILDE
   * - RETRO_KEYBOARD_KEY_UNDERSCORE
   */
  switch (keycode) {
  case KEY_CLEAR: /* 0x163 */
    return RETRO_KEYBOARD_KEY_CLEAR;
  case  KEY_MODE: /* 0x175 */
    return RETRO_KEYBOARD_KEY_MODE;
  case KEY_BREAK: /* 0x19b */
    return RETRO_KEYBOARD_KEY_BREAK;
  case KEY_DOLLAR: /* 0x1b2 */
    return RETRO_KEYBOARD_KEY_DOLLAR;
  case KEY_EURO: /* 0x1b3 */
    return RETRO_KEYBOARD_KEY_EURO;
  default:
    return RETRO_KEYBOARD_KEY_UNKNOWN;
  }

}

guint
retro_keyboard_key_to_val_converter (RetroKeyboardKey key)
{
  /*
   * US-ASCII codes
   *
   * Both GDK_KEY_* and RETRO_KEYBOARD_KEY_* start with the US-ASCII codes,
   * implementing common letters, digits and symbols.
   */
  if (key >= 0x20 && key < 0x80)
    return key;

  /*
   * Function keys
   *
   * Both GDK_KEY_F* and RETRO_KEYBOARD_KEY_F* implement function keys 1—15 in a
   * consecutive manner. GDK_KEY_F* actually implements more function keys but
   * RETRO_KEYBOARD_KEY_F* doesn't.
   */
  if (key >= RETRO_KEYBOARD_KEY_F1 && key <= RETRO_KEYBOARD_KEY_F15)
    return GDK_KEY_F1 + (key - RETRO_KEYBOARD_KEY_F1);

  /*
   * Keypad digits
   *
   * Both GDK_KEY_KP_* and RETRO_KEYBOARD_KEY_KP* implement keypad digits 0–9 in
   * a consecutive manner.
   */
  if (key >= RETRO_KEYBOARD_KEY_KP0 && key <= RETRO_KEYBOARD_KEY_KP9)
    return GDK_KEY_KP_0 + (key - RETRO_KEYBOARD_KEY_KP0);

  /*
   * Various keys
   *
   * FIXME: The following keys are unimplemented because I couldn't find the
   * right GDK_KEY_* equivalent:
   * - RETRO_KEYBOARD_KEY_MODE
   * - RETRO_KEYBOARD_KEY_COMPOSE
   * - RETRO_KEYBOARD_KEY_POWER
   */
  switch (key) {
  case RETRO_KEYBOARD_KEY_BACKSPACE:
    return GDK_KEY_BackSpace;
  case RETRO_KEYBOARD_KEY_TAB:
    return GDK_KEY_Tab;
  case RETRO_KEYBOARD_KEY_CLEAR:
    return GDK_KEY_Clear;
  case RETRO_KEYBOARD_KEY_RETURN:
    return GDK_KEY_Return;
  case RETRO_KEYBOARD_KEY_PAUSE:
    return GDK_KEY_Pause;
  case RETRO_KEYBOARD_KEY_ESCAPE:
    return GDK_KEY_Escape;
  case RETRO_KEYBOARD_KEY_DELETE:
    return GDK_KEY_Delete;

  case RETRO_KEYBOARD_KEY_UP:
    return GDK_KEY_Up;
  case RETRO_KEYBOARD_KEY_DOWN:
    return GDK_KEY_Down;
  case RETRO_KEYBOARD_KEY_LEFT:
    return GDK_KEY_Left;
  case RETRO_KEYBOARD_KEY_RIGHT:
    return GDK_KEY_Right;
  case RETRO_KEYBOARD_KEY_INSERT:
    return GDK_KEY_Insert;
  case RETRO_KEYBOARD_KEY_HOME:
    return GDK_KEY_Home;
  case RETRO_KEYBOARD_KEY_END:
    return GDK_KEY_End;
  case RETRO_KEYBOARD_KEY_PAGEUP:
    return GDK_KEY_Page_Up;
  case RETRO_KEYBOARD_KEY_PAGEDOWN:
    return GDK_KEY_Page_Down;

  case RETRO_KEYBOARD_KEY_KP_PERIOD:
    return GDK_KEY_KP_Decimal;
  case RETRO_KEYBOARD_KEY_KP_DIVIDE:
    return GDK_KEY_KP_Divide;
  case RETRO_KEYBOARD_KEY_KP_MULTIPLY:
    return GDK_KEY_KP_Multiply;
  case RETRO_KEYBOARD_KEY_KP_MINUS:
    return GDK_KEY_KP_Subtract;
  case RETRO_KEYBOARD_KEY_KP_PLUS:
    return GDK_KEY_KP_Add;
  case RETRO_KEYBOARD_KEY_KP_ENTER:
    return GDK_KEY_KP_Enter;
  case RETRO_KEYBOARD_KEY_KP_EQUALS:
    return GDK_KEY_KP_Equal;

  case RETRO_KEYBOARD_KEY_NUMLOCK:
    return GDK_KEY_Num_Lock;
  case RETRO_KEYBOARD_KEY_CAPSLOCK:
    return GDK_KEY_Caps_Lock;
  case RETRO_KEYBOARD_KEY_SCROLLOCK:
    return GDK_KEY_Scroll_Lock;
  case RETRO_KEYBOARD_KEY_RSHIFT:
    return GDK_KEY_Shift_R;
  case RETRO_KEYBOARD_KEY_LSHIFT:
    return GDK_KEY_Shift_L;
  case RETRO_KEYBOARD_KEY_RCTRL:
    return GDK_KEY_Control_R;
  case RETRO_KEYBOARD_KEY_LCTRL:
    return GDK_KEY_Control_L;
  case RETRO_KEYBOARD_KEY_RALT:
    return GDK_KEY_Alt_R;
  case RETRO_KEYBOARD_KEY_LALT:
    return GDK_KEY_Alt_L;
  case RETRO_KEYBOARD_KEY_RMETA:
    return GDK_KEY_Meta_R;
  case RETRO_KEYBOARD_KEY_LMETA:
    return GDK_KEY_Meta_L;
  case RETRO_KEYBOARD_KEY_RSUPER:
    return GDK_KEY_Super_R;
  case RETRO_KEYBOARD_KEY_LSUPER:
    return GDK_KEY_Super_L;

  case RETRO_KEYBOARD_KEY_HELP:
    return GDK_KEY_Help;
  case RETRO_KEYBOARD_KEY_PRINT:
    return GDK_KEY_Print;
  case RETRO_KEYBOARD_KEY_SYSREQ:
    return GDK_KEY_Sys_Req;
  case RETRO_KEYBOARD_KEY_BREAK:
    return GDK_KEY_Break;
  case RETRO_KEYBOARD_KEY_MENU:
    return GDK_KEY_Menu;
  case RETRO_KEYBOARD_KEY_EURO:
    return GDK_KEY_EuroSign;
  case RETRO_KEYBOARD_KEY_UNDO:
    return GDK_KEY_Undo;

  default:
    return GDK_KEY_VoidSymbol;
  }
}
